main.c: OK!
includes/structs.h: OK!
includes/cub3d.h: OK!
includes/define.h: OK!
includes/libft/ft_toupper.c: OK!
includes/libft/ft_tolower.c: OK!
includes/libft/ft_split.c: OK!
includes/libft/ft_memcpy.c: OK!
includes/libft/ft_lstsize.c: OK!
includes/libft/ft_strnstr.c: OK!
includes/libft/ft_isalnum.c: OK!
includes/libft/ft_strlcat.c: OK!
includes/libft/ft_strchr.c: OK!
includes/libft/ft_lstiter.c: OK!
includes/libft/ft_isdigit.c: OK!
includes/libft/ft_itoa.c: OK!
includes/libft/ft_lstclear.c: OK!
includes/libft/ft_strlcpy.c: OK!
includes/libft/ft_strrchr.c: OK!
includes/libft/ft_isprint.c: OK!
includes/libft/libft.h: OK!
includes/libft/ft_isascii.c: OK!
includes/libft/ft_lstadd_front.c: OK!
includes/libft/ft_strjoin.c: OK!
includes/libft/ft_lstmap.c: OK!
includes/libft/ft_striteri.c: OK!
includes/libft/ft_strncmp.c: OK!
includes/libft/ft_putchar_fd.c: OK!
includes/libft/ft_memset.c: OK!
includes/libft/ft_strlen.c: OK!
includes/libft/ft_atoi.c: OK!
includes/libft/ft_strmapi.c: OK!
includes/libft/ft_lstlast.c: OK!
includes/libft/ft_bzero.c: OK!
includes/libft/ft_substr.c: OK!
includes/libft/ft_putstr_fd.c: OK!
includes/libft/ft_strdup.c: OK!
includes/libft/ft_isalpha.c: OK!
includes/libft/ft_lstdelone.c: OK!
includes/libft/ft_lstnew.c: OK!
includes/libft/ft_memchr.c: OK!
includes/libft/ft_memmove.c: OK!
includes/libft/ft_lstadd_back.c: OK!
includes/libft/ft_putendl_fd.c: OK!
includes/libft/ft_putnbr_fd.c: OK!
includes/libft/ft_strtrim.c: OK!
includes/libft/ft_memcmp.c: OK!
includes/libft/ft_calloc.c: OK!
includes/get_next_line/get_next_line.c: OK!
includes/get_next_line/get_next_line_utils.c: OK!
includes/get_next_line/get_next_line.h: OK!
parsing/check_matrix.c: OK!
parsing/check_continue.c: OK!
parsing/other_init.c: OK!
parsing/parsing_map.c: OK!
parsing/map_checks.c: OK!
parsing/other_checks.c: OK!
parsing/init_data.c: OK!
events/close.c: OK!
events/some_other_mlx.c: OK!
events/some_mlx.c: OK!
events/moves.c: OK!
free_all/free_data.c: OK!
free_all/free_cub.c: OK!
window/init_cub.c: OK!
window/player_init.c: OK!
window/my_pxl.c: OK!
window/minimap2.c: OK!
window/sprites.c: OK!
window/init_win.c: OK!
window/minimap.c: OK!
math/fmap.c: OK!
raycasting/raycasting2.c: OK!
raycasting/dda.c: OK!
raycasting/dda2.c: OK!
raycasting/draw2.c: OK!
raycasting/sword.c: OK!
raycasting/raycasting.c: OK!
raycasting/draw.c: OK!
